#+TITLE: suboptimal 
#+AUTHOR: Alexander Phillips
#+EMAIL: mail@alexanderphillips.net
-----

Suboptimal is a minimalistic command line interface (CLI) subtitle finder written in Rust. It works for any video, movie or TV show you have! If the subtitles exist on a publically available database online, suboptimal will find and download it for you.

Currently, suboptimal uses the SubDB API to pull subtitles, with more APIs to added soon.

* Installation

There are three different options here: installation through the package manager, manual installation of the binary or manual installation after building it from source.

** Package Manager

This is the simplest option if you use the pacman package manager. You can navigate to the [[https://github.com/Tatsuonline/suboptimal/releases][releases]] tab and download the package named suboptimal-1.0-1-x86_64.pkg.tar.xz.

Run the installation:

#+BEGIN_SRC bash
pacman -U suboptimal-1.0-1-x86_64.pkg.tar.xz
#+END_SRC

I will try to add this package into AUR later to make it even easier.

** Manual Installation Of The Binary

Navigate to the [[https://github.com/Tatsuonline/suboptimal/releases][releases]] tab and download the binary named suboptimal.

Manually install it:

#+BEGIN_SRC bash
mv suboptimal /usr/bin/
#+END_SRC

** Manual Installation After Building From Source

Clone this repository:

#+BEGIN_SRC bash
git clone https://github.com/Tatsuonline/suboptimal.git
#+END_SRC

Build the release:

#+BEGIN_SRC bash
cargo build --release
#+END_SRC

Install it:

#+BEGIN_SRC bash
cargo install --path .
#+END_SRC

* Documentation

#+BEGIN_SRC bash
suboptimal 0.1.0
Finds and downloads subtitles for videos.

USAGE:
    suboptimal [FLAGS] [OPTIONS] <file>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    -v, --verbose    Prints details as the program runs

OPTIONS:
    -l, --language <language>    Specifies the language of the subtitles to download [default: en]

ARGS:
    <file>    The path to the file or directory of files for which to get subtitles for
#+END_SRC
